### ISSUE TITLE
Route Handler not called

### ISSUE THREAD

**Issue by bolencki13** [hapijs/jwt#17]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): YES
* *is this issue affecting a production system?* (yes/no): This version is not in production yet, however it is blocking our upcoming release.

#### Context

* *node version*: 12.14.0
* *module version with issue*: 2.0.0
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): node
* *used with* @hapi/hapi
* *any other relevant information*: I am using typescript

#### What are you trying to achieve or the steps to reproduce?
I have managed to setup the plugin with a Hapi.Server instance with the following [config](https://github.com/hapijs/jwt/issues/15#issuecomment-683755670). Upon successful authentication, my actual route is not being called. I am able to have my routes hit when I remove the plugin.

#### What was the result you got?
No routes are called after authentication.

#### What result did you expect?
Routes to be called after authentication.

**Comment by devinivy** [comment]
When you say the "route is not called" you mean that your route's `handler` is never running, is that correct?  I took a look at the config you linked to, but overall there is not enough information here to help you out.  Can you provide a runnable reproduction of your issue?  At minimum the contents of the HTTP requests being made and responses you're getting back would be a great place to start.

**Comment by bolencki13** [comment]
Yes, apologizes for the wrong terminology. The handler is not being called. I've written a barebones examplehttps://github.com/bolencki13/hapi-jwt-example and pushed it to [this repo](https://github.com/bolencki13/hapi-jwt-example). I don't see a response from the secured endpoint.

**Comment by devinivy** [comment]
No problem 👍 .  I see what is going on— your repro is using a feature that is shown in the docs but not fully explained.  Your `validate` function is returning three properties: `{ isValid, credentials, response }`.  That final property `response`, when set, indicates that you would like to immediately respond to the request.  In hapi parlance this is a ("takeover response"](https://github.com/hapijs/hapi/blob/master/API.md#takeover-response).  If you just omit that property from your jwt `validation` function you should see the request continue through the request lifecycle to your handler 👍 .  We would certainly take a PR to improve the documentation for this!
