### ISSUE TITLE
Load the JWT from an arbitrary location in the request

### ISSUE THREAD

**Issue by abeluck** [hapijs/jwt#28]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes 
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.15.1
* *module version*: 2.0.1
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...): app
* *any other relevant information*: n/a

#### What problem are you trying to solve?

Currently hapi/jwt only supports variations of the HTTP Authorization header. We need to be able to load the JWT from an arbitrary place in the request.

We'd also like to be able to pick the requests from a Cookie, and other arbitrary headers.

#### Do you have a new or modified API suggestion to solve the problem?

There are a couple different ways to approach this. One would be to explicitly support various methods (cookie, header name etc). But another more flexible way would be to accept a function that takes the request and returns the token. This would like stem off future requests of "..but we want to get the token from XXX"

**Comment by abeluck** [comment]
I'd be happy to draw up a PR for this, but would like to get some feedback first regarding which approach to take.

**Comment by devinstewart** [comment]
@abeluck, are you still interested in drawing up a PR for this?

I personally am intrigued by the idea.  The caveat being that if you do nothing, it defaults to grabbing it out of the HTTP Authorization header.

This would avoid a "Breaking Change" release.

**Comment by devinstewart** [comment]
There has been no movement on this for a bit.  I'm going to leave it open, however going to give my 2¢ that while allowing the JWT from anywhere is _possible_, it is not  _recommended_.  

I personally don't want to be involved in a module that leaked tokens due to a valid misuse

Query Params come to mind, putting your tokens in other's log files if `Referrer-Policy` is not set correctly.

If others disagree I'm all ears.

**Comment by sorsaffari** [comment]
Considering that storing the JWT token in a cookie is (arguably) considered a better practice, it'd be great if the plugin can be configured to read the token from a cookie by a given name.

**Comment by abeluck** [comment]
I agree @devinstewart . I would also support an approach that does not allow storing the JWT anywhere.

In addition to the Authorization header I think there are two more options that should be allowed:

* Cookies, by name
* Headers, by name

**Comment by lallenfrancisl** [comment]
This is pretty much a standard feature thats really needed. Could I work on this ? After briefly glossing over the code, what I understood is the tasks that have to be done are 

- exposing a config field for cookie name
- exposing a config config field for header name
- using these settings in the token 

And I believe this could be done in this function https://github.com/lallenfrancisl/jwt/blob/36b38fd18dbd79fcbf242405599e9e0da8b5f5df/lib/plugin.js#L229

**Comment by lallenfrancisl** [comment]
Are there any libraries that are being used by hapi modules in common to parse cookie headers ? Or do I just write the code to parse it here itself ?

**Comment by lallenfrancisl** [comment]
I have made a PR addressing this issue #43 here
