### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by giraffesyo** [hapijs/jwt#30]
Hello, thank you for open sourcing this. Are there any typescript typings available for this module?

**Comment by devinstewart** [comment]
There are not.  I have always been interested in TS typings.  If you are willing to do some PR's I can assist you approvals and help get them pulled in.

And after I pick up the hang of it, I could possibly do some myself.

I use Angular as a frontend framework, so I work with TypeScript, but have never created my own typings.

**Comment by devinstewart** [comment]
Closing as typescript support will be handled by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

Thank you @ssanchezmarc for creating this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50945).
