### ISSUE TITLE
A journey through testing

### ISSUE THREAD

**Issue by devinstewart** [hapijs/jwt#31]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  12
* *module version*: 2.0.1
* *environment* (e.g. node, browser, native): node 
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

While implementing a fix last week, I ran into what was a truly baffling experience with testing.  
The tests were intermittently failing when the `node-forge` package was doing a `Forge.pki.certificateFromPem` in the mock that creates the `x5c` of the JSON Web Key Set.  
What I found interesting that inside a nested chain of `node-forge` commands was this block that converts the certificate to a PEM then back to a certificate:
```js
Forge.pki.certificateFromPem(Forge.pki.certificateToPem(cert))
```
Feeling this was unnecessary I removed the the back and forth to only leave the line:
```js
const certDer = Forge.util.encode64(Forge.asn1.toDer(Forge.pki.certificateToAsn1(cert)).getBytes());
key.x5c = [certDer];
```

When doing this, I was getting errors in two particular tests not always but more often then the error above where it was expecting the output of **Steve**, but getting a 500 Error.

So I put an additional parameter in those two tests `reformat: true` and put the following condition in the mock:
```js
let certDer;
if (options.reformat) {
    certDer = Forge.util.encode64(Forge.asn1.toDer(Forge.pki.certificateToAsn1(Forge.pki.certificateFromPem(Forge.pki.certificateToPem(cert)))).getBytes());
}
else {
    certDer = Forge.util.encode64(Forge.asn1.toDer(Forge.pki.certificateToAsn1(cert)).getBytes());
}

key.x5c = [certDer];
```
This did not eliminate the issue, but reduced the surface area in which `Forge.pki.certificateFromPem` was called, making the tests much more consistent.  However, with 18 flavors of the tests running (3 versions of Node x 2 versions of hapi x 3 Operating systems), it still showed up from time to time.  This is where the code stands today.

This evening I decided to add the option `{ retry: true }` to the `script.describe()` for the `Plugin` as this is where all the JWKS mocks are.

To my surprise, every single test under this option passes after a second try.  This happens both locally (where I was rarely getting a failure) and on GitHub Actions.  The results are consistent.

At this point I am going to attach a PR to this issue with this change.  I have two questions for the community:

1. Is this an acceptable solution?
2. Does someone have any idea why every test would take two tries to pass with the `retry` option on, when most of them pass on the first try with it off?

**Comment by cjihrig** [comment]
Flaky tests are a real problem across the org, and the problem has been a bit worse since moving from Travis to GitHub Actions because Actions require all of the configurations to be re-run.

However, I think we should try to fix those tests when possible, and add `retry` to only individual tests.

**Comment by devinstewart** [comment]
Thank you for the feedback Colin.  I have updated the PR to only `retry` on the two tests that are Flaky.  All tests for all 18 combinations passed with 10 runs of GitHub Actions on my local repo.

Believe me I would love nothing **more** than to have these tests pass outright.  But all the tricks I have up my sleeve came up short.

If you or somebody approves this PR I will gladly open a new issue that asks to address the Flakiness of these two tests and see if someone in the community can think of something I have not.

That way I can get to addressing some of bugs and feature requests in the queue of this repo.
