### ISSUE TITLE
node-forge function causing Public RSA tests to be flaky

### ISSUE THREAD

**Issue by devinstewart** [hapijs/jwt#33]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  12
* *module version*: 2.0.1
* *environment* (e.g. node, browser, native): node 
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### How can we help?

To run two tests that use Public RSA keys the following code is required to test the `x5c` of the key:

```js
certDer = Forge.util.encode64(Forge.asn1.toDer(Forge.pki.certificateToAsn1(Forge.pki.certificateFromPem(Forge.pki.certificateToPem(cert)))).getBytes());

key.x5c = [certDer];
```

The `node-forge` command occasionally throws an error when running the `Forge.pki.certificateFromPem()` function.  The error is not always the same, but when it happens my observation has always been that it was from this function.  It is more common when running GitHub Actions.

At this time  `{ retry: true }` is set on those two tests.  Any help in finding the true cause of this flaky behavior would be welcomed.

**Comment by kanongil** [comment]
My guess is that the `cert` is corrupted somehow. Maybe from to the [`serialNumber`](https://github.com/hapijs/jwt/blob/355939488e11b1255598915019b90252240c3123/test/mock.js#L38), which is passed as a [base64ish](https://github.com/hapijs/cryptiles/blob/15722165c0c1a6a411389188f4b780ca0441ccce/lib/index.js#L13-L18) string, while it expects a hex string.

**Comment by devinstewart** [comment]
@kanongil As usual your guess is correct!  I will be raising a PR this weekend to fix and undo all of the "workaround" code.

I can then **finally** get going on that bug you found with token encoding.

Thanks as always.
