### ISSUE TITLE
No changelog for v3.0.0

### ISSUE THREAD

**Issue by ghostdevv** [hapijs/jwt#51]
#### Context

* *node version*: n/a
* *module version*: v3.0.0

#### What are you trying to achieve or the steps to reproduce ?

Unable to find a github release or changelog on the website

**Comment by Marsup** [comment]
Sorry for not getting back to you sooner, you can find all the changes in the corresponding milestone https://github.com/hapijs/jwt/milestone/11?closed=1. It happens when the changes are trivial that we don't always publish release notes, but we always trace it with milestone assigned issues.

**Comment by ghostdevv** [comment]
Thanks for providing some information, it was quite alarming when a major version was published but I couldn't find any information about why :sweat_smile:
